### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by bwhmather** [bwhmather/ssort#33]
Python 3.10 introduces pattern matching, which looks just as much of a pain to add support for as the walrus operator.  Simply ignoring pattern matching is not an option as patterns introduce bindings which may be relied on later.

**Comment by bwhmather** [comment]
I've marked this as a good first issue because it should mostly be a case of repeating code that already exists, but with minor alterations.  If you are interested in getting stuck into ssort development, then this is where to volunteer.

**Comment by jgberry** [comment]
Hey @bwhmather, I’m interested in taking a crack at this one.

I’ve started to through around some code [here](https://github.com/jgberry/ssort/tree/py310).

**Comment by bwhmather** [comment]
Yes, please!

With two caveats, I would also very much like to see a PR for your bindings change, as it seems likely that it fixes more than just the issues you identified.  The two caveats are:
  - In the past (3+ years ago) I've found `ast.NodeVisitor` to be enormously and inexplicably slow.  I think it would be worth doing a few adhoc benchmarks before merging.
  - The order that the bindings are yielded in has been significant in the past, although it shouldn't be anymore.  I don't think it matters if we change the order, but the order should be stable between runs.  Keep the tests as `list`.

**Comment by jgberry** [comment]
Thanks for the feedback @bwhmather.

I agree these bindings changes most likely decrease performance; however, the magnitude of the decrease I am unsure of. I'll try to put together some benchmarks to gauge the severity.

Before filing a pull request for these changes, I'd also like to take a look at the `_requirements` and `_method_requirements` modules which, at first glance, would also seem to benefit from an overhaul similar to the one I did for the `_bindings` module. The key change to these modules is to move from explicit handling of all AST node types to only handling special case nodes. Then, all non-special case nodes can be handled generically which decreases code complexity and makes adding new AST nodes, such as the pattern matching nodes, much simpler.

Since the above changes are fairly large, in the meantime, I'll file a minimal pull request with the `FormattedValue` fix.

**Comment by bwhmather** [comment]
RE benchmarks:  I usually just scan my poetry cache with the `--check` flag enabled.  No need to be too precise.  With that said, thank you for being careful.

**Comment by jgberry** [comment]
Support for Python 3.10 was added in #45

**Comment by bwhmather** [comment]
:+1:

**Comment by bwhmather** [comment]
Have released as part (most) of version 0.11.2.
